sudo: required
services:
  - docker
before_install:
  - docker build -t nuthanc/docker-react -f Dockerfile.dev .
script:
  - docker run nuthanc/docker-react npm run test -- --coverage 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-704181274243"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"